baseURL = "https://coderturtle.githubpages.io/first-90-days"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Head of Architecture - First 90 Days"
theme = "hugo-learn-theme"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/coderturtle/first-90-days"
  description = "Example of first 90 days reviewing an architecture thene"
  author = "Derm Duncan"
  themeVariant = "blue"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableMermaid = false
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  titleSeparator = "::"

[outputs]
home = [ "HTML", "RSS", "JSON"]

ignoreLogs = ['error-remote-getjson']

[Languages]
[Languages.en]
title = "Head of Architecture First 90 Days"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/coderturtle/first-90-days"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> Showcases"
url = "https://coderturtle.githubpages.io/first-90-days"
weight = 11

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Hugo Documentation"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20
